# Generated by Django 4.1.7 on 2023-02-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_User_ID', models.SmallIntegerField()),
                ('Current_TM_ID', models.SmallIntegerField()),
                ('Current_Team_ID', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrashMonsters',
            fields=[
                ('TM_ID', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
    ]
