# Generated by Django 4.1.7 on 2023-02-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashmonsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashmonsters',
            name='TM_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
