# Generated by Django 4.1.7 on 2023-03-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trashmonsters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trashmonsters",
            name="TM_Name",
            field=models.CharField(default="Name Not Set*", max_length=512),
        ),
    ]
