# Generated by Django 4.1.7 on 2023-02-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashmonsters', '0002_alter_trashmonsters_tm_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counters',
        ),
        migrations.AddField(
            model_name='trashmonsters',
            name='Team1_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trashmonsters',
            name='Team2_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trashmonsters',
            name='Team3_Score',
            field=models.IntegerField(default=0),
        ),
    ]
