# Generated by Django 4.1.7 on 2023-02-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trashusers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trashusers.team",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_gamekeeper",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_player",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=10),
        ),
    ]
