# Generated by Django 4.1.6 on 2023-02-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trashusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trashusers.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_gamekeeper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_player',
            field=models.BooleanField(default=False),
        ),
    ]
