# Generated by Django 4.1.7 on 2023-03-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trashusers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
