# Generated by Django 4.1.7 on 2023-03-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trashusers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GkEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
