# Generated by Django 4.1.7 on 2023-02-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trashusers', '0002_player_team_user_is_gamekeeper_user_is_player'),
        ('trashmonsters', '0002_alter_trashmonsters_tm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('monster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trashmonsters.trashmonsters')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trashusers.team')),
            ],
        ),
    ]
