# Generated by Django 4.1.6 on 2023-02-22 16:32

from django.db import migrations, models
import django.db.models.deletion
import trashimages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trashusers', '0002_player_team_user_is_gamekeeper_user_is_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trashusers.team')),
            ],
        ),
    ]
