# Generated by Django 4.1.6 on 2023-02-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trashusers', '0002_player_team_user_is_gamekeeper_user_is_player'),
        ('trashimages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashimages',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trashusers.team'),
        ),
    ]
