# Generated by Django 4.1.7 on 2023-03-17 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashimages', '0004_images_m_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='m_id',
        ),
    ]
