name: Deploy to remote VPS
env:
  API_KEY: ${{ secrets.SECRET_KEY }}
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ 22 }}
        script: |
          cd ../home/trashmuncher/Trash-Muncher-Webapp
          git stash
          git pull
          ./run-docker.sh
