---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: trashmuncher-backend-image
      PROJECT_ID: kinetic-star-380414
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest europe-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest europe-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/$IMAGE_NAME:$GIT_TAG
        docker push europe-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/$IMAGE_NAME:latest
        docker push europe-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/$IMAGE_NAME:$GIT_TAG
