on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      uses: appleboy/ssh-action@master
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ../home/trashmunchers/Trash-Muncher-Webapp
          git pull
          ./run-docker.sh
